services:
  zookeeper:
    platform: linux/amd64
    container_name: zookeeper
    image: zookeeper:3.5.10
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1

  coordinator:
    platform: linux/amd64
    image: apache/druid:30.0.0
    container_name: coordinator
    depends_on:
      - zookeeper
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment

  broker:
    platform: linux/amd64
    image: apache/druid:30.0.0
    container_name: broker
    depends_on:
      - zookeeper
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment

  historical:
    platform: linux/amd64
    image: apache/druid:30.0.0
    container_name: historical
    depends_on: 
      - zookeeper
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment

  middlemanager:
    platform: linux/amd64
    image: apache/druid:30.0.0
    container_name: middlemanager
    depends_on: 
      - zookeeper
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - environment

  router:
    platform: linux/amd64
    image: apache/druid:30.0.0
    container_name: router
    depends_on:
      - zookeeper
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment

networks:
  default:
    external: true
    name: netflix-net
